workflows:
  android-release:
    name: Android Release
    max_build_duration: 30
    environment:
      flutter: stable
      groups: []
    scripts:
      - name: Generate fresh Android files
        script: |
          mkdir -p /tmp/project
          cd /tmp/project
          flutter create --org com.example --project-name meu_app .
          cd /Users/builder/clone
          rm -rf android
          cp -r /tmp/project/android android
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing: {}